### ISSUE TITLE
All packages return 404 or client errors

### ISSUE THREAD

**Issue by mjancarik** [pd4d10/npmview#2]
Hi,

I try view package react and others but I always return 404 page or client errors.

buttons.esm.87b24c20.js:1 Uncaught (in promise) TypeError: Cannot read property 'createElement' of undefined
    at buttons.esm.87b24c20.js:1
index.9855a46f.js:71 Uncaught (in promise) TypeError: t is not a function
    at index.9855a46f.js:71

**Comment by pd4d10** [comment]
Thanks for the feedback!

It should have been ready now: https://npmview.now.sh/react

> buttons.esm.87b24c20.js:1 Uncaught (in promise) TypeError: Cannot read property 'createElement' of undefined
at buttons.esm.87b24c20.js:1
index.9855a46f.js:71 Uncaught (in promise) TypeError: t is not a function
at index.9855a46f.js:71

This module still have a little problem. Let's keep this issue open to track it.

**Comment by mjancarik** [comment]
Thanks, for me works everything well now.
